all: 1 2 3 5 6 7 8 9 10 11

1: 1.cpp
	mpic++ -o 1 1.cpp

2: 2.cpp
	mpic++ -o 2 2.cpp

3: 3.cpp
	mpic++ -o 3 3.cpp

5: 5.cpp
	mpic++ -fopenmp -o 5 5.cpp

6: 6.cpp
	mpic++ -fopenmp -o 6 6.cpp

7: 7.cpp
	mpic++ -fopenmp -o 7 7.cpp

8: 8.cpp
	mpic++ -fopenmp -o 8 8.cpp

9: 9.cpp
	mpic++ -fopenmp -o 9 9.cpp

10: 10.cpp
	mpic++ -o 10 10.cpp

11: 11.cpp
	mpic++ -fopenmp -o 11 11.cpp

clean:
	rm 1 2 3 5 6 7 8 9 10 11